---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Docs


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:
    paths:
      - 'docs/**'
      - '!**.md'
  # Runs on master Branch and Tags
  push:
    paths:
      - 'docs/**'
      - '!**.md'
    branches:
      - master


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - build
          - linkcheck
          # - linkcheck2

    name: "[Docs ${{ matrix.target }}]"
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Check documentation
        uses: cytopia/shell-command-retry-action@v0.1.3
        with:
          retries: 5
          workdir: "${{ github.workspace }}/docs/"
          command: |
            make ${{ matrix.target }}
