---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  # Note: Older PHP versions use an older version of phpPgMyAdmin, which does not work with later
  # PgSQL server versions. That's why we need to tell those combinations to use an old PgSQL server
  MATRIX: >-
    [
      {"PHP_SERVER": "PHP 5.3", "HTTPD_SERVER": "apache-2.2", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.4", "HTTPD_SERVER": "apache-2.2", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.5", "HTTPD_SERVER": "apache-2.2", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.6", "HTTPD_SERVER": "apache-2.2", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.0", "HTTPD_SERVER": "apache-2.2", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.1", "HTTPD_SERVER": "apache-2.2", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.2", "HTTPD_SERVER": "apache-2.2"},
      {"PHP_SERVER": "PHP 7.3", "HTTPD_SERVER": "apache-2.2"},
      {"PHP_SERVER": "PHP 7.4", "HTTPD_SERVER": "apache-2.2"},
      {"PHP_SERVER": "PHP 8.0", "HTTPD_SERVER": "apache-2.2"},
      {"PHP_SERVER": "PHP 8.1", "HTTPD_SERVER": "apache-2.2"},
      {"PHP_SERVER": "PHP 8.2", "HTTPD_SERVER": "apache-2.2"},

      {"PHP_SERVER": "PHP 5.3", "HTTPD_SERVER": "apache-2.4", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.4", "HTTPD_SERVER": "apache-2.4", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.5", "HTTPD_SERVER": "apache-2.4", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.6", "HTTPD_SERVER": "apache-2.4", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.0", "HTTPD_SERVER": "apache-2.4", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.1", "HTTPD_SERVER": "apache-2.4", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.2", "HTTPD_SERVER": "apache-2.4"},
      {"PHP_SERVER": "PHP 7.3", "HTTPD_SERVER": "apache-2.4"},
      {"PHP_SERVER": "PHP 7.4", "HTTPD_SERVER": "apache-2.4"},
      {"PHP_SERVER": "PHP 8.0", "HTTPD_SERVER": "apache-2.4"},
      {"PHP_SERVER": "PHP 8.1", "HTTPD_SERVER": "apache-2.4"},
      {"PHP_SERVER": "PHP 8.2", "HTTPD_SERVER": "apache-2.4"},

      {"PHP_SERVER": "PHP 5.3", "HTTPD_SERVER": "nginx-stable", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.4", "HTTPD_SERVER": "nginx-stable", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.5", "HTTPD_SERVER": "nginx-stable", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.6", "HTTPD_SERVER": "nginx-stable", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.0", "HTTPD_SERVER": "nginx-stable", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.1", "HTTPD_SERVER": "nginx-stable", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.2", "HTTPD_SERVER": "nginx-stable"},
      {"PHP_SERVER": "PHP 7.3", "HTTPD_SERVER": "nginx-stable"},
      {"PHP_SERVER": "PHP 7.4", "HTTPD_SERVER": "nginx-stable"},
      {"PHP_SERVER": "PHP 8.0", "HTTPD_SERVER": "nginx-stable"},
      {"PHP_SERVER": "PHP 8.1", "HTTPD_SERVER": "nginx-stable"},
      {"PHP_SERVER": "PHP 8.2", "HTTPD_SERVER": "nginx-stable"},

      {"PHP_SERVER": "PHP 5.3", "HTTPD_SERVER": "nginx-mainline", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.4", "HTTPD_SERVER": "nginx-mainline", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.5", "HTTPD_SERVER": "nginx-mainline", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 5.6", "HTTPD_SERVER": "nginx-mainline", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.0", "HTTPD_SERVER": "nginx-mainline", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.1", "HTTPD_SERVER": "nginx-mainline", "PGSQL_SERVER": "PgSQL 12"},
      {"PHP_SERVER": "PHP 7.2", "HTTPD_SERVER": "nginx-mainline"},
      {"PHP_SERVER": "PHP 7.3", "HTTPD_SERVER": "nginx-mainline"},
      {"PHP_SERVER": "PHP 7.4", "HTTPD_SERVER": "nginx-mainline"},
      {"PHP_SERVER": "PHP 8.0", "HTTPD_SERVER": "nginx-mainline"},
      {"PHP_SERVER": "PHP 8.1", "HTTPD_SERVER": "nginx-mainline"},
      {"PHP_SERVER": "PHP 8.2", "HTTPD_SERVER": "nginx-mainline"}
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      matrix:
        description: "The determined version matrix"
        value: ${{ jobs.params.outputs.matrix }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: "[Set-Output] Matrix"
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$( echo '${{ env.MATRIX }}' | jq -M -c )"

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Matrix'
          echo '--------------------'
          echo '${{ steps.set-matrix.outputs.matrix }}'
          echo
